language: rust
rust:
  - 1.2.0
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ precise universe multiverse"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ precise-updates universe multiverse"
  - sudo apt-get update -q
  - sudo apt-get install -y libsdl2-dev
